### ISSUE TITLE
Preconfigure or automate installations of ctfd 

### ISSUE THREAD

**Issue by jonakarl** [CTFd/CTFd#2457]
I am not sure if it is possible (at least I have not seen it documented) to automate installations of ctfd. 

My goal is to automatically deploy ctfd as docker services that is ready to run and to achieve this I need to automate: 
1. Disabling of the setup wizard 
2. Configuration of  a admin user and set or acquire a admin token (via api calls or environment variables to the docker container)

Alternatively:
1. Be able to pre-configure the values of the setup wizard and "admin  token".
    -   Either via environment variables or by hard coding them in the build phase of the docker image.   

Is this in anyway possible ?

**Comment by pve** [comment]
I think if you look in our code (link above) for SETUP_EVENT_ADMIN you will find what you need. 
There is still work to do on this, so let's work together.

**Comment by pve** [comment]
The general idea is to do this through environment variables and/or the config.ini file. In our Kubernetes setup we feed the environment variables through a configmap.

**Comment by pandatix** [comment]
Hi @jonakarl !

[We](https://github.com/ctfer-io) had the same problem regarding the first install of a CTFd, later configuration drift recovery and finally CTF replicability.
To solve this problem we scripted things as @pve did for the JCR, but were not satisfied enough...
We ended up creating [ctfd-setup](https://github.com/ctfer-io/ctfd-setup) that solves the setup and pages configuration problem.

The core idea is, as I recommend it, that through a `.ctfd.yaml` file you can use a key=value setup to simply configure your CTFd instances from a bare-install.
If you use a YAML extension in your IDE, you'll see this file has autocompletion to ease usage ! :tada: 
One example follows.

```yaml
appearance:
  name: "My CTF !"
  description: "Some super duper content"

theme:
  logo:
    from_file: logo.png
  small_icon:
    from_file: small-icon.png
  name: core-beta
  header:
    from_file: theme-header.html

settings:
  challenge_visibility: public
  account_visibility: public
  score_visibility: private
  registration_visibility: public

mode: teams

admin:
  name: 'ctfer'
  email: 'ctfer-io@protonmail.com'
  password:
    from_env: ADMIN_PASSWORD

pages:
  additional:
    - title: My CTF !
      route: index
      format: markdown
      content:
        from_file: index.html
```

Then you can execute `ctfd-setup`, and in a few seconds everything is prod-ready.

```bash
ctfd-setup --url http://localhost:8000 --file .ctfd.yaml
```

As your use-case seems to be docker-based, I ping @NicoFgrx for details of its internal usage for developments ; an extract follows.

```yaml
# docker-compose.yml

# create a "ctfd" service

  ctfd-setup:
    image: ctferio/ctfd-setup:v1.5.2
    environment:
      URL: http://ctfd:8000
      FILE: /.ctfd.yaml
    volumes:
      - .ctfd.yaml:/.ctfd.yaml
    networks:
      - testing
    depends_on:
      ctfd:
        condition: service_healthy
```

For specific cases, we use [additional scripts](https://github.com/ctfer-io/terraform-provider-ctfd/blob/main/cmd/token/main.go) in [GitHub workflows](https://github.com/ctfer-io/terraform-provider-ctfd/blob/main/.github/workflows/ci.yaml#L68-L73).

Hope it helps you ! :smile:
