### ISSUE TITLE
How to Deploy CTFd on Coolify?

### ISSUE THREAD

**Issue by luthfihalimii** [CTFd/CTFd#2749]
Can someone help me how to deploy CTFd in Coolify?

**Comment by jruedaq** [comment]
use this docker-compose file 

```
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_ROOT_PASSWORD=ctfd
    volumes:
      - db_data:/var/lib/mysql

  cache:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

  ctfd:
    image: ctfd/ctfd:latest
    depends_on: [db, cache]
    environment:
      - SECRET_KEY=pon_un_valor_aleatorio_largo
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db:3306/ctfd
      - REDIS_URL=redis://cache:6379/0
      - UPLOAD_FOLDER=/var/uploads
      - LOG_FOLDER=/var/log/CTFd
      - WORKERS=2
      - REVERSE_PROXY=True
    volumes:
      - ctfd_uploads:/var/uploads
      - ctfd_logs:/var/log/CTFd
      - ctfd_themes:/opt/CTFd/CTFd/themes/custom  # ← persistente para tus temas
    expose:
      - "8000"   # deja que el proxy de Coolify enrute

volumes:
  db_data:
  redis_data:
  ctfd_uploads:
  ctfd_logs:
  ctfd_themes:
```
