### ISSUE TITLE
[Warning] Access denied for user 'root'@'172.18.0.3' (using password: NO)

### ISSUE THREAD

**Issue by Colbert337** [CTFd/CTFd#585]
**Environment**:

  - CTFd Version/Commit: version:1.1.2/Latest commit 4dd828a  13 days ago
  - Operating System: ubuntu16.04_64
  - Web Browser and Version:QQ Browser9.7(13014)
  -Docker version 1.13.1, build 092cba3
  -docker-compose version 1.20.0-rc1, build 86428af

**What happened?**
[Warning] Access denied for user 'root'@'172.18.0.3' (using password: NO)

**What did you expect to happen?**
No Warning 

**How to reproduce your issue**
git clone https://github.com/CTFd/CTFd.git
cd CTFd/
sudo docker-compose up

**Any associated stack traces or error logs**

```
version: '2'

services:
  ctfd:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - LOG_FOLDER=/var/log/CTFd
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
    networks:
        default:
        internal:

  db:
    image: mariadb:10.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800]
```

```
ubuntu@VM-92-69-ubuntu:~/CTFd$  sudo docker-compose up
Starting ctfd_db_1 ... done
Starting ctfd_ctfd_1 ... done
Attaching to ctfd_db_1, ctfd_ctfd_1
ctfd_1  | Waiting on MySQL
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] mysqld (mysqld 10.2.13-MariaDB-10.2.13+maria~jessie) starting as process 1 ...
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: Uses event mutexes
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: Using Linux native AIO
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: Number of pools: 1
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: Using SSE2 crc32 instructions
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: Completed initialization of buffer pool
db_1    | 2018-03-10  3:19:30 140617692313344 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: Highest supported file format is Barracuda.
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: 128 out of 128 rollback segments are active.
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: Waiting for purge to start
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] InnoDB: 5.7.21 started; log sequence number 1655794
db_1    | 2018-03-10  3:19:30 140617531242240 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1    | 2018-03-10  3:19:30 140618434119552 [Note] Plugin 'FEEDBACK' is disabled.
db_1    | 2018-03-10  3:19:30 140617531242240 [Note] InnoDB: Buffer pool(s) load completed at 180310  3:19:30
db_1    | 2018-03-10  3:19:31 140618434119552 [Note] Server socket created on IP: '::'.
db_1    | 2018-03-10  3:19:31 140618434119552 [Warning] 'proxies_priv' entry '@% root@6c68ce57318d' ignored in --skip-name-resolve mode.
db_1    | 2018-03-10  3:19:31 140618434119552 [Note] Reading of all Master_info entries succeded
db_1    | 2018-03-10  3:19:31 140618434119552 [Note] Added new Master_info '' to hash table
db_1    | 2018-03-10  3:19:31 140618434119552 [Note] mysqld: ready for connections.
db_1    | Version: '10.2.13-MariaDB-10.2.13+maria~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```

**db_1    | 2018-03-10  3:19:31 140618127435520 [Warning] Access denied for user 'root'@'172.18.0.3' (using password: NO)**

```
ctfd_1  | ..Ready
ctfd_1  | Starting CTFd
ctfd_1  |  * Loaded module, <module 'CTFd.plugins.challenges' from '/opt/CTFd/CTFd/plugins/challenges/__init__.py'>
```
